Update Checkin.yml

diff --git a/.github/workflows/Checkin.yml b/.github/workflows/Checkin.yml
--- a/.github/workflows/Checkin.yml
+++ b/.github/workflows/Checkin.yml
@@ -177,11 +177,8 @@ jobs:
           dotnet-version: 5.0.x
       - name: Publish
         run: |
-          cd checkin
-          dotnet restore
-          dotnet build --configuration Release --no-restore
-          cd ./src/Ray.BiliBiliTool.Console
-          dotnet publish --self-contained false -o ./bin/Publish/net5-dependent
+          cd checkin/src/Ray.BiliBiliTool.Console
+          dotnet publish --configuration Release --self-contained false --output ./bin/Publish/net5-dependent
       - name: Run APP
         id: bilibili_checkin
         env:
@@ -192,9 +189,8 @@ jobs:
           Ray_Security__IsSkipDailyTask: ${{secrets.BILI_ISSKIPDAILYTASK}}
           Ray_Security__UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36"
         run: |
-          cd checkin
-          cd ./src/Ray.BiliBiliTool.Console/bin/Publish/net5-dependent
-          dotnet Ray.BiliBiliTool.Console.dll -closeConsoleWhenEnd=1 ${{secrets.OTHERCONFIGS}} || echo "::set-output name=status::Error"
+          cd checkin/src/Ray.BiliBiliTool.Console/bin/Publish/net5-dependent
+          dotnet Ray.BiliBiliTool.Console.dll -runTasks=Daily -closeConsoleWhenEnd=1 ${{secrets.OTHERCONFIGS}} || echo "::set-output name=status::Error"
       - name: Set Python
         if: steps.bilibili_checkin.outputs.status == 'Error'
         uses: actions/setup-python@v2
