Update Checkin.yml

diff --git a/.github/workflows/Checkin.yml b/.github/workflows/Checkin.yml
--- a/.github/workflows/Checkin.yml
+++ b/.github/workflows/Checkin.yml
@@ -57,7 +57,7 @@ jobs:
           python-version: 3.x
       - name: Install dependencies
         run: |
-          git clone -b master --depth 1 https://github.com/xirikm/hostloc-auto-get-points checkin
+          git clone --depth 1 https://github.com/xirikm/hostloc-auto-get-points checkin
           python -m pip install --upgrade requests pyaes
       - name: Get points
         id: hostloc_get_points
@@ -83,7 +83,7 @@ jobs:
           python-version: 3.6
       - name: Install dependencies
         run: |
-          git clone -b master --depth 1 https://github.com/ghosx/tieba checkin
+          git clone --depth 1 https://github.com/ghosx/tieba checkin
           python -m pip install --upgrade requests
       - name: Check in
         id: tieba_checkin
@@ -108,15 +108,48 @@ jobs:
           python-version: 3.x
       - name: Install dependencies
         run: |
-          git clone -b master --depth 1 https://github.com/t00t00-crypto/cloud189-action checkin
+          git clone --depth 1 https://github.com/mengshouer/CheckinBox checkin
           pip3 install -r checkin/requirements.txt
       - name: Checkin
         id: cloud189_checkin
+        env:
+          username: ${{ secrets.CLOUD189_USER }}
+          password: ${{ secrets.CLOUD189_PW }}
         run: |
-          user='${{ secrets.CLOUD189_USER }}'
-          pwd='${{ secrets.CLOUD189_PWD }}'
-          echo -e "$user\n$pwd" > tmp
-          python3 checkin/checkin.py < tmp || echo "Error"
+          python checkin/Cloud189Checkin/C189CheckinForSCF.py > msg && cat msg
+          [[ $(grep '出错' msg) ]] && echo "::set-output name=status::Error" || true
+      - uses: actions/checkout@v2
+        if: steps.cloud189_checkin.outputs.status == 'Error'
+      - name: Notify
+        if: steps.cloud189_checkin.outputs.status == 'Error'
+        run: python Notify.py '天翼云盘'
+
+  pojie:
+    name: 52Pojie Check in
+    runs-on: ubuntu-latest
+    steps:
+      - name: Sleep Random Time
+        run: sleep $(shuf -i 10-60 -n 1)
+      - name: Set Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.x
+      - name: Install dependencies
+        run: |
+          git clone --depth 1 https://github.com/mengshouer/CheckinBox checkin
+          pip3 install -r checkin/requirements.txt
+      - name: Checkin
+        id: pojie_checkin
+        env:
+          cookie_52pj: ${{ secrets.PJ_COOKIE }}
+        run: |
+          python checkin/Checkin52pj/Checkin52pjForSCF.py > msg && cat msg
+          [[ $(grep '失效|出错' msg) ]] && echo "::set-output name=status::Error" || true
+      - uses: actions/checkout@v2
+        if: steps.pojie_checkin.outputs.status == 'Error'
+      - name: Notify
+        if: steps.pojie_checkin.outputs.status == 'Error'
+        run: python Notify.py '吾爱破解'
   
   pt_checkin:
     name: PT Sites Check in
@@ -129,7 +162,7 @@ jobs:
           URL: ${{ secrets.FLEXGET_CONFIG_URL }}
         run: |
           mkdir /tmp/config
-          git clone https://github.com/IvonWei/flexget_qbittorrent_mod.git /tmp/config/plugins
+          git clone --depth 1 https://github.com/IvonWei/flexget_qbittorrent_mod.git /tmp/config/plugins
           curl -L ${{ secrets.FLEXGET_CONFIG_URL }} -o /tmp/config/config.yml
           docker run -d --name flexget -v /tmp/config:/config madwind/flexget
           sleep 60 && docker exec flexget flexget execute && docker rm -f flexget
@@ -143,7 +176,7 @@ jobs:
       - name: Set time zone
         run: sudo timedatectl set-timezone 'Asia/Shanghai'
       - name: Clone
-        run: git clone https://github.com/RayWangQvQ/BiliBiliTool checkin
+        run: git clone --depth 1 https://github.com/RayWangQvQ/BiliBiliTool checkin
       - name: Setup .NET
         uses: actions/setup-dotnet@v1
         with:
@@ -186,7 +219,7 @@ jobs:
       - name: Sleep Random Time
         run: sleep $(shuf -i 10-60 -n 1)
       - name: Clone
-        run: git clone https://github.com/jiegto/Actions_smzdm checkin
+        run: git clone --depth 1 https://github.com/jiegto/Actions_smzdm checkin
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
