Update Experience.yaml

diff --git a/.github/workflows/Experience.yaml b/.github/workflows/Experience.yaml
--- a/.github/workflows/Experience.yaml
+++ b/.github/workflows/Experience.yaml
@@ -23,7 +23,7 @@ jobs:
         with:
           python-version: 3.x
       - name: Install dependencies
-        run: python -m pip install --upgrade requests pyaes 
+        run: python -m pip install --upgrade requests pyaes flexget Pillow matplotlib pandas
       - name: BYZH Experience
         env:
           COOKIE: ${{ secrets.BYZH_COOKIE }}
@@ -33,11 +33,24 @@ jobs:
           HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
           HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
         run: python Experience/hostloc.py || echo "HOSTLOC_FAIL=true" >> $GITHUB_ENV
+      - name: PT Sites
+        env:
+          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
+          FLEXGET_CONFIG_URL: ${{ secrets.FLEXGET_CONFIG_URL }}
+        run: |
+          mkdir flexget && cd flexget
+          curl -sSL \
+            -H "Authorization: token $REPO_TOKEN" \
+            $FLEXGET_CONFIG_URL \
+            > config.yaml
+          git clone https://github.com/madwind/flexget_qbittorrent_mod plugins
+          flexget -c config.yaml execute --task sign_in || echo "FLEXGET_FAIL=true" >> $GITHUB_ENV
       - name: Notify
-        if: env.BYZH_FAIL || env.HOSTLOC_FAIL
+        if: env.BYZH_FAIL || env.HOSTLOC_FAIL || env.FLEXGET_FAIL
         run: |
           [ $BYZH_FAIL ] && python Notify.py '不移之火'
           [ $HOSTLOC_FAIL ] && python Notify.py 'Hostloc'
+          [ $FLEXGET_FAIL ] && python Notify.py 'Flexget'
   
   epic_free_games:
     name: Epic Claimer
